### ISSUE TITLE
スクロールバーいいかんじにする

### ISSUE THREAD

**Issue by ygkn** [AI-create-team/WriterLighter#22]

**Comment by ygkn** [comment]
スクロールは闇()

**Comment by Happa8** [comment]
スクロールバー関連のプラグインと行ったらこれかな。
旧WLで導入しようとしたもののうまく行かんかった…
http://manos.malihu.gr/jquery-custom-content-scroller/

**Comment by ygkn** [comment]
同じく。
他のやつとも格闘してみたが…

**Comment by ygkn** [comment]
CSSで `::-webkit-scrollbar` 使えばいいそう
http://csspro.digitalskill.jp/%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB/webkit-%E3%82%B9%E3%82%AF%E3%83%AD%E3%83%BC%E3%83%AB%E3%83%90%E3%83%BC-%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3/
