### ISSUE TITLE
Electron 1.0対応

### ISSUE THREAD

**Issue by ygkn** [AI-create-team/WriterLighter#27]

**Comment by ygkn** [comment]
閉じてなかった（）
最近多い気をつけなければ

**Comment by ygkn** [comment]
やったこととしては、
`window.remote = window.require 'remote'`
=> 
`window.remote = window.require('electron').remote`
にしたのと、`remote` 下のモジュール(`Menu`,`dialog`など)を`remote.require()`から`remote.moduleName`にした

**Comment by Happa8** [comment]
んな簡単に1.0対応できたのか

**Comment by ygkn** [comment]
ミスでreopenしましたごめんちゃい
