### ISSUE TITLE
脱 bower !

### ISSUE THREAD

**Issue by ygkn** [AI-create-team/WriterLighter#62]
- [x] jQuery -> npmのjqueryに以降
- [x] jQuery UI Plug-in -> 自前で作る
- [ ] 章のsortable -> [voidberg/html5sortable](https://github.com/voidberg/html5sortable)
- [ ] suggest-> [onozaty/suggest.js](https://github.com/onozaty/suggest.js)

**Comment by ygkn** [comment]
@KawakawaRitsuki Y did U close?

**Comment by mizucoffee** [comment]
Sorry,I made an operational mistake :k

**Comment by ygkn** [comment]
ok ;)
